name: Update Quote

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with a new quote
        run: |
          QUOTE=$(shuf -n 1 assets/quotes.txt)
          sed -i '/<!--QUOTE_START-->/, /<!--QUOTE_END-->/c\> <!--QUOTE_START-->\n> '"$QUOTE"'\n> <!--QUOTE_END-->' README.md
      - name: Commit changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git commit -am "Update daily quote"
          git push
